### ISSUE TITLE
 The type or namespace name `Plugins' cannot be found (2018.3.11)

### ISSUE THREAD

**Issue by Firemaw** [Jimmar/Permission-Please#2]
Having an issue after upgrading from 2017.4 (working) to 2018.3.11f1. The following compile errors occur in the Editor:

> Assets/PermissionPleaseExample/Scripts/Example.cs(1,7): error CS0246: The type or namespace name 'Plugins' could not be found. Are you missing an assembly reference?
> Assets/PermissionPleaseExample/Scripts/TestAllPermissions.cs(4,7): error CS0246: The type or namespace name 'Plugins' could not be found. Are you missing an assembly reference?
> Assets/PermissionPleaseExample/Scripts/Example.cs(17,34): error CS0246: The type or namespace name 'PermissionPlease' could not be found. Are you missing an assembly reference?
